config/routes.rb
Rails.application.routes.draw do
  
  resources :pages do
    get :upvote,    on: :member
    get :expensive, on: :collection
  end

  
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base

  has_many :comments, as: :commentable

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  belongs_to :user  
  has_many :positions
  has_many :pages

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :user

end

app/models/page.rb
class Page < ActiveRecord::Base

  validates :name, presence: true

  has_many :positions
  has_many :carts, through: :positions
  has_many :comments, as: :commentable

end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :page
  belongs_to :cart

end

app/models/user.rb
class User < ActiveRecord::Base

  has_one   :cart
  has_many  :orders
  has_many  :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception

  private

  def render_403
    render file: "public/403.html", status: 403
  end

  def render_404
    render file: "public/404.html", status: 404
  end

  def check_if_admin
    render_403 unless params[:admin]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_filter :verify_authenticity_token
	before_filter :find_page,				only: [:show, :edit, :update, :destroy, :upvote]
	#before_filter :check_if_admin,	only: [:edit, :update, :destroy]

	#/pages
  def index
    @pages = Page.all
    #@pages = @pages.where("webelement_count >= ?", params[:webelement_count]) if params[:webelement_count]
    #@pages = @pages.where("created_at >= ?", 1.day.ago) if params[:today]
    #@pages = @pages.order("name ASC")
  end

  def expensive
  	@pages = Page.where("webelement_count > 3")
  	render :index
  end

  #/pages/1 GET
  def show
  	unless @page
  		render text: "Page not found", status: 404
  	end
  end

  #/pages/new GET
  def new
  	@page = Page.new
  end

  #/pages/1/edit GET
  def edit
  end

  #/pages POST
  def create
    @page = Page.create(page_params)
    if @page.errors.empty?
    	redirect_to action: "index"
    else 
    	render "new"
    end
  end

  #/pages/1 PUT
  def update
  	@page.update_attributes(page_params)
    if @page.errors.empty?
      flash[:success] = "Item successfully updated"
    	redirect_to page_path(@page)
    else 
      flash.now[:error] = "You made mistakes in your form. please correct them"
    	render "edit"
    end
  end

  #/pages/1 DELETE
  def destroy
  	@page.destroy
  	redirect_to action: "index"
  end

  #/pages/1/upvote
  def upvote
  	@page.increment!(:votes_count)
  	redirect_to action: "index"
  end

  def page_params
    params.require(:page).permit(:name, :url, :description, :webelement_count)
  end

  private

  def find_page
		@page = Page.where(id: params[:id]).first
		render_404 unless @page
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p style="color: red"><%= flash[:error]%></p>
<p style="color: green"><%= flash[:success]%></p>
<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<p style="color: red"><%= flash[:error] %></p>

<p><%= f.input :name %></p>
<p><%= f.input :url %></p>
<p><%= f.input :description, as: :text %></p>
<p><%= f.input :webelement_count %></p>

app/views/pages/edit.html.erb
<h1>Edit page</h1>

<%= simple_form_for @page do |f| %>

	<%= render partial: "form", locals: { f: f } %>
	
	
	<button type="button" class="btn btn-error"><%= f.submit "Save Changes" %></button>

<% end %>

app/views/pages/index.html.erb
<h1>Home Page</h1>

<% if @pages.empty? %>
	<b>No pages in store</b>
<% else %>

<table>
	<tr>
		<th>ID<th/>
		<th>NAME<th/>
		<th>DESCRIPTION<th/>
		<th>RATING</th>
	</tr>

	<% @pages.each do |p| %>
		<tr>
			<td><%= p.id %></td>
			<td><%= link_to p.name, page_path(p) %><td/>
			<td><%= p.description %></td>
			<td><%= link_to "Delete", p, method: :delete, data: { confirm: "Are you shure?" } %></td>
			<td><%= link_to "Edit", edit_page_path(p) %></td>
			<td><%= p.votes_count%>, <%= link_to "+", upvote_page_path(p) %></td>
		</tr>


	<% end %>
</table>	
<button>Create <%=  %> </button>>

<% end %>

app/views/pages/new.html.erb
<h1>Create new page</h1>

<%= simple_form_for @page do |f| %>

	<%= render partial: "form", locals: { f: f } %>
	
	<p><%= f.submit "Create page" %></p>

<% end %>

app/views/pages/show.html.erb
<h1>Show page</h1>
<h1><%= @page.name %></h1>

<ul>
	<li>URL: <%= @page.url %></li>
	<li>Webelement_count: <%= @page.webelement_count %></li>
	<li>Description: <%= @page.description %></li>
  <button>Go back to Home page <%=  %></button>
</ul>>

<form action="/pages" method="POST"> 
</form>